/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import datos.LoginDAO;
import dominio.Login;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author leelu
 */
public class LOGIN extends javax.swing.JFrame {
    public static String usr, tip;
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_logout = new javax.swing.JButton();
        txt_logear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTRASEÑA:");

        txt_usuario.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USUARIO:");

        txt_contraseña.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_logout.setText("CANCELAR");
        txt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_logoutActionPerformed(evt);
            }
        });

        txt_logear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_logear.setText("ACCEDER");
        txt_logear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_logearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_logear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_logout))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_logear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_logearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_logearActionPerformed
    String vcontraseña, vestado, vusuario, vtipo;
    
    LoginDAO logindao = new LoginDAO();
    Login loginbuscar = new Login();
    loginbuscar.setUsuario(txt_usuario.getText());
    loginbuscar= logindao.query(loginbuscar);
    
        if (loginbuscar.getId()!=null) {
            
            vusuario = loginbuscar.getUsuario();
            vcontraseña = loginbuscar.getContraseña();
            vestado = loginbuscar.getEstado();
            vtipo = loginbuscar.getTipo();
            
            if (vcontraseña.equals(txt_contraseña.getText())&&vestado.equals("1")) {
                try{
                    usr=loginbuscar.getUsuario();
                    tip=vtipo;
                    MDI contenedor = new MDI();
                    contenedor.setVisible(true);
                    this.dispose();
                
                }catch (Exception e) {
                        System.out.println(e);
                }
            }else{
               JOptionPane.showMessageDialog(null, "ERROR AL INICIAR SESIÓN"); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "USUARIO NO REGISTRADO");
        }
    
    
    }//GEN-LAST:event_txt_logearActionPerformed

    private void txt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_logoutActionPerformed
    int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea SALIR del programa?", "Cerrar Programa", JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        } 
    }//GEN-LAST:event_txt_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //FLATLAF
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JButton txt_logear;
    private javax.swing.JButton txt_logout;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
